### ISSUE TITLE
Differences in posterior probabilities for `Asia` example network

### ISSUE THREAD

**Issue by jaeckdaniel** [MaxHalford/hedgehog#17]
Hi Max,

thanks so much for setting up such a great library with a very clean and concise API!

I have a quick question regarding the posterior probabilities of the `Asia` network example:

If I select `Dispnea` as query variable and no event variables in your [demo app](https://hedgehog-demo.herokuapp.com/), I get the following posterior probabilities:

```
Dispnea P(Dispnea)
0       0.5640
1       0.4360
```

These are also the values that you see in other sources using the `Asia` example (e.g., [Bayes Server](https://www.bayesserver.com/examples/networks/asia) or [Netica](https://www.norsys.com/WebHelp/NETICA/X_Example_Bayes_Net.htm))

If I run the following code in Python (`3.9.2`), I get the following posterior probabilities for the `Dispnea` node:

```python
>>> import hedgehog as hh
>>> bn = hh.examples.asia()
>>> bn.query("Dispnea", event={})

Dispnea
False    0.602547
True     0.397453
Name: P(Dispnea), dtype: float64
```

Do you know what is causing these differences, or am I using the API incorrectly?

Thanks a lot!
Daniel

**Comment by MaxHalford** [comment]
Good catch! I had introduced a typo when tidying the probability tables. It's fixed now. Cheers!

**Comment by jaeckdaniel** [comment]
Thanks so much for the quick fix, @MaxHalford . Cheers!
